name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull na Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd24052025:latest

      - name: Remove no Container
        run: docker rm -f ci-cd24052025 || true

      - name: Rodando container
        run: docker run --name ci-cd24052025 -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd24052025:latest